--- #YAML:1.0
name:                Lingua-EN-NameParse
version:             1.23
abstract:            Manipulate peoples names, titles and initials
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Parse::RecDescent:             0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kim Ryan
