--- #YAML:1.0
name:                Lingua-EN-NameParse
version:             1.27
abstract:            Manipulate peoples names, titles and initials
license:             perl
author:              
    - Kim Ryan
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
    Parse::RecDescent:             0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
