---
abstract: 'Manipulate peoples names, titles and initials'
author:
  - 'Kim Ryan <kimryan at cpan org>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.04
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EN-NameParse
provides:
  Lingua::EN::NameParse:
    file: lib/Lingua/EN/NameParse.pm
    version: 1.31
  Lingua::EN::NameParse::Grammar:
    file: lib/Lingua/EN/NameParse/Grammar.pm
    version: 1.30
requires:
  Parse::RecDescent: 1
  Test::Pod::Coverage: 1.04
  locale: 1
  strict: 1.04
  utf8: 1.09
  warnings: 1.12
resources:
  license: http://dev.perl.org/licenses/
version: 1.31
